baseURL = "https://gorgonia.org/"
languageCode = "en-us"
metadataformat = "yaml"
title = "Gorgonia - Deep Learning Library for Go"
theme = "docdock"

disqusShortname = ""
googleAnalytics = ""
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
    name = "Gorgonia"
    author = "Gorgonia Authors"
    description = "Gorgonia is a suite of libraries for creating performant deep learning and machine learning applications in Go"
    editURL = "https://github.com/gorgonia/gorgonia.github.io/tree/master/src/content/"
    themeStyle = "flex" # "original" or "flex" # default "flex"
    copyright = "Released under the MIT license"
    enableGitInfo = true
    ordersectionsby = "weight" # ordersectionsby = "title"


[outputs]
    home = ["HTML", "RSS", "JSON"]


[[menu.shortcuts]]
    pre = "<h3>More</h3>"
    name = "<i class='fa fa-github'></i> <label>Github repo</label>"
    identifier = "ds"
    url = "https://github.com/gorgonia/gorgonia"
    weight = 10

[[menu.shortcuts]]
    name = "<i class='fa fa-bookmark'></i> <label>GoDoc</label>"
    identifier = "godoc"
    url = "https://godoc.org/gorgonia.org/gorgonia"
    weight = 20

